version: '2.2'

services:
  db:
    image: postgres:11.5
    ports:
      - "5432:5432"
    volumnes:
      - postgres:/var/lib/postgresql/data

  web:
    build: .
    command: bin/rails server --port 3000 --binding 0.0.0.0
    ports:
      - "3000:3000"
    volumes:
      - .:/myapp

volumes:
  postgres: